languageCode = "en-us"
languageName = "English"
title = "Ixtlan Designs"
weight = 1

[params]
  description = "Custom web development, design, and digital solutions for businesses"

[params.author]
  name = "Ixtlan Designs"
  email = "info@ixtlandesigns.com"
