[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Services"
  url = "/services"
  weight = 20

[[main]]
  name = "Hugo Migration"
  url = "/hugo-migration"
  weight = 25

[[main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 30

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 60
