[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Services"
  url = "/services"
  weight = 20

[[main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 30

[[main]]
  name = "Cardistry"
  url = "/ionrot"
  weight = 40

[[main]]
  name = "Sounds"
  url = "/sounds"
  weight = 50

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 60
