colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

disableImageOptimization = false
disableTextInHeader = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  cardView = false

[article]
  showDate = true
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = true

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  groupByYear = true
  cardView = false

[taxonomy]
  showTermCount = true
  showBreadcrumbs = false

[term]
  showBreadcrumbs = false
  groupByYear = false
