baseURL = 'https://bowevil.github.io/ixtlandesigns/'
languageCode = 'en-us'
title = 'Ixtlan Designs'
theme = 'ixtlan'
canonifyURLs = true

[params]
  description = "Efficient Impeccable Development and Design"
  copyright = "2015 Ixtlan Designs"
  phone = "(321) 345-3001"
  email = "info@ixtlandesigns.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Cardistry"
    url = "/ionrot/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Sounds"
    url = "/sounds/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
